credentials:
  usernames:
    cdgonzalezr_eeeu:
      email: elchristog@gmail.com
      name: Christian Gonzalez
      password: $2b$12$4AWFIxVL40AYHNdxrEbUQ.bvqTqbJV0tLLtY4myqWTklf4fhNKSZa
    jeamartinezcu:
      email: jeimy855@gmail.com
      name: Alejandra Martinez
      password: $2b$12$4AWFIxVL40AYHNdxrEbUQ.bvqTqbJV0tLLtY4myqWTklf4fhNKSZa
    lfmartinezs:
      email: lufermartinez1985@gmail.com
      name: Luisa Martinez
      password: $2b$12$4HfjCRGeboCMCvQyzD70.u3JMUvSV0mgDrDkMpwcZRXk4QprY9TSi
    testcustomer:
      email: elchristog@gmail.com
      name: Christian Gonzalez
      password: $2b$12$4AWFIxVL40AYHNdxrEbUQ.bvqTqbJV0tLLtY4myqWTklf4fhNKSZa
    jumaruizz:
      email: juliamariaruiz1@gmail.com
      name: Julia Ruiz
      password: $2b$12$Fmhn4ilWz2KfpUKz4NgzB.V7Uh0pICzsUu6RhdeNQH2RFbRAn6nC2
    yesntiranoes:
      email: escobar_9420@hotmail.com
      name: Yeisson Tirano
      password: $2b$12$qUVARWuLj0WBPzluAQG0M./r6rmI3G26ZxK4sk6u3KPNVehTXa6pC
    prmartince:
      email: marin.pris1983@gmail.comm
      name: Priscilla Cervantes
      password: $2b$12$SHze82ShGY/goUqugqqcL.lzaDHqC.lct9sGVK15YXjuZqyzf3jT2
    dslealc:
      email: didavidsantt@hotmail.es
      name: Santiago Leal
      password: $2b$12$mRSiosSXaSQchnkcUIsZ2OoHXCu0UJY46C4DkmXzyg.zDaB1dJr7s
    lgmatar:
      email: laumata21@gmail.com
      name: Laura Mata
      password: $2b$12$QocVs3Edg3XsBhq9wE.yHe1uoN0U6bOvZhhgoF1goLAFzofsFQuj2
    cgomezva:
      email: camila.gomezvasquez@gmail.com
      name: Camila Gomez
      password: $2b$12$9Mg5MHeENF4OfwUKHrcI0ujOnX7UAmsdxojE/FARHC9AYPeZWdI9S
    sdburitacam:
      email: saradanellyburitica@gmail.com
      name: Sara Buritica
      password: $2b$12$uk.FYLsUKHdrbroVfMsLj.CbM1bBeW8zwIC5hX3KbKkCd15VVcaq2
    lvrestrepom:
      email: vialaya@hotmail.com
      name: Luz Restrepo
      password: $2b$12$KVuBsj/PARlyKQX7JO1wg.H/0/gpjFgdmb8khQhnC.7TMPZn9OgQG
    marenas:
      email: ymarenascardenas@gmail.com
      name: Marcela Arenas
      password: $2b$12$Z4AijPo7xw2KIC1KMffgMediWjI67u0NSNBuQnRQveiwjJf2MYb.e
    alespitia:
      email: espitiaarizaangielorena@gmail.com
      name: Angie Espitia
      password: $2b$12$saspEq7hp2Xir3UFN9HOxOZf4Sw7ZNd4v4nJHYXZPXc5JS32x6zum
    mparboledap:
      email: Michellearboleda909@gmail.com 
      name: Paola Arboleda
      password: $2b$12$MePjMYL/3yDuiG68JrU07e.vzpQ6gbCeAOUpYZGJKDyS0MoA3RZgW
    iramirez:
      email: yeseniaramirez.ee@gmail.comm
      name: Ivette Ramirez
      password: $2b$12$cNpeIX8nZfsUa1viIl91SeHTUtQbts1VvhKwLExRyckCWKzWyxB4a
    tacalizarazo:
      email: taniakmila0810@hotmail.com
      name: Tatiana Lizaraso
      password: $2b$12$iJoa3kiqXyUZNJFh3JM7OOw.RNN2jkjYoRdHkHiS.ui.oMU2kvGPa
    bingleyodiaz:
      email: bingleyo.diaz@hotmail.com
      name: Bingley Ortiz
      password: $2b$12$gsJNdu16gcAYdeXqI5u6s.nfaQRNYFQI/Q1Re36Rh41VoSmjbpB9K
    ytmanrrique:
      email: yaneetyancemanrrique@gmail.com
      name: Yaneet Manrrique
      password: $2b$12$MxmAD1xgfdhxRCuq1u3Rt.73JjtLo9H5894D7L2cVwkryuJP54.OK
    ippadillac:
      email: paola6_17@hotmail.com
      name: Paola Padilla
      password: $2b$12$o7cYeNig1551ve0bBP8Jju9UtGiU0PmsMeTm0XNwjJukegeiyYvm6
    lvortizb:
      email: liseth1102@ocloud.com
      name: Liseth Ortiz
      password: $2b$12$bNhEKonEUVv4xf4H5eF34u9n6bWzDgMG72u7oIp3ZNHNXYPm.iXp6
    malejandraag:
      email: mayraariasga@gmail.com 
      name: Mayra Arias
      password: $2b$12$oEjiWzPuyLs8CrDXfH4mHOK6/vMDFAWszp191EuJhRmlP9/jIDXEu
    lgurbano:
      email: gelijulumar@gmail.com
      name: Lizagoretty Urbano
      password: $2b$12$PZTYN.aGa91jmkYCKYSoOugoMEt8EwhRkaJGV5/g3klU7lDvoD7ay
    jvduartea:
      email: vivi.duartea23@gmail.com
      name: Viviana Duarte
      password: $2b$12$4QNIVrpb9HPb2xVyNXnzQ.C51HK8apZASSB/WM8DirRnIm6QhkZTy
    dstephaniehr:
      email: dshernandezr23@gmail.com
      name: Dayanne Stephanie Hernandez Romero
      password: $2b$12$RX3rjHugTJ63YHDozVhGaOwXNc2w58Rr2.FjaZsqyS3sIfqDHKaO.
    erodriguezmr:
      email: eva66803@gmail.com
      name: Eva Rodriguez
      password: $2b$12$PIDhj9dsWv/Bj7LUnrU5yenyqShZ/XnDPzyn2FmxyJrxli9KvC.iO
    jacruzr:
      email: javierandrescruz01@gmail.com
      name: Andres Cruz
      password: $2b$12$o5ooT1q..xhismvyF1uk.enTuEqeRMRqkgzSrcfc8sw826aJxNETa
    tmosoresf:
      email: tatianaosoresfdez@gmail.com
      name: Tatiana Osores
      password: $2b$12$Ole9WkshxBxrxD3gCS2zaO/cx7Iw0/CJ1FpCpW3WQw0W7ZlYFJkn2
    lnoguera:
      email: lavaju1982@gmail.com
      name: Lady Noguera
      password: $2b$12$5vYxizZ/q6O8veH13cB48uf05kjoBi0zlJ2s.XMZHZAm3xyUKHfpK
    trafficker0231:
      email: trafficker0231@gmail.com
      name: trafficker0231
      password: $2b$12$lCiYym4L1bxOKXKxPOzLOOlnmTHaJC/Uq.TMzjfyUPj7w/RdpoDeK
    smperezg:
      email: marci.94@icloud.com
      name: Sleyter Perez
      password: $2b$12$6o4yu5IN7f7dGGVv0jpgPeEv1BJCuxqMiDT6so2u3nuGkDfTqqEju
    editor_0176:
      email: videoeditor@enfermeraenestadosunidos.com
      name: editor_0176
      password: $2b$12$.pxAEZaONqBvknuZf1lXn.Fd75vJmBvxMigA.GqjFl6mBQ21KUWmW
    amesquivelc:
      email: esquivelamanda22@gmail.com
      name: Amanda Esquivel
      password: $2b$12$Ln4VA9vNMRxvbaTaX2EyTuKeAfnIbRAwaKeiaEoMC6wjJDVOhlWhi
    lmvergaran:
      email: myriamverni@gmail.com
      name: Myriam Vergara
      password: $2b$12$Qg9ptxbIeSqhm/Ywo5BCSe5vjEw946ASfmsBg8m3eWdJy5bH9AvUO
    jacruzr_eeeu:
      email: javierandrescruz01@gmail.com
      name: Andres Cruz
      password: $2b$12$o5ooT1q..xhismvyF1uk.enTuEqeRMRqkgzSrcfc8sw826aJxNETa
    yabarreto:
      email: yumibase93@gmail.com
      name: Yumi Barreto
      password: $2b$12$H7JG6a1BCedpD1txFt3xD..pLi55UTMoYfkyC6s5h6.tIhr4AyhUq
    jasotog:
      email: julianitasogo@gmail.com
      name: Juliana Soto
      password: $2b$12$0eFGw.5AZ6r50PDVLdDni.mzRmVwpjLUuRXnpNvJRyxlcnHA2kmPK
    mmayangaf:
      email: meri.mf3092@gmail.com
      name: Merilin Mayanga
      password: $2b$12$1S3zbFUIJ7Jd34jUPOHsieT5Zuvxox9dSlyLIYG3YPmy528t3h1k2
    eapereda:
      email: erikprogrem@gmail.com
      name: Erik Pereda
      password: $2b$12$X6l5dZFQ/dawpXkuAeIbHOc1qWBnjaGky7Dj9AtuZR8afNWQ5D9MC
    dflefio:
      email: df.lefio@gmail.com
      name: Daniela Lefio
      password: $2b$12$Umr6fMTef1pjLhQ5F8z5C.z/qJpyzhWuWlKZ0Sm98qIMHSNOY2OKO
    isanchezc:
      email: 1irenesanchez2011@gmail.com
      name: Irene Sanchez
      password: $2b$12$9fKPfrbZgJi0dDTcNCzFYOtIowMuNSVT47AmRZjR.EfabYkMotWrO
    bynavam:
      email: brenda.navamtz15@gmail.com
      name: Brenda Nava
      password: $2b$12$3SM7qwASrma8McYIyuiLKunL83Q5EA1IqdR6NVsUSzZZIYwgi/fbe
    editor_1875:
      email: videoeditor@enfermeraenestadosunidos.com
      name: editor_1875
      password: $2b$12$AJE.ncfwbfaHotx.mm9vOOpXdidpcqxsWh3qHGj4fE4oCaRgTud0y
    cmgomezm:
      email: gomezcmilena@gmail.com
      name: Milena Gomez
      password: $2b$12$HzRa1aA1Nx7qOM4o1kYwVuzbgXQE60aI95NDk85Txesw2Te1.mWCW
    paespitias:
      email: espitiapaula01@gmail.com
      name: Paula Espitia
      password: $2b$12$zOz3TwbIDujNcR18um5Ih.Ebwqq/1OyclORbvyKLveTRiLcekSncW
    pltaform_dev_976:
      email: pltaform_dev_976@enfermeraenestadosunidos.com
      name: pltaform_dev_976
      password: $2b$12$o9XGPnch7uX9l/UqFEKuTOsq.aXYyapMBBotKh7HknfH0TO/7g7EW
    meposada:
      email: marianaestrella16@hotmail.com
      name: Mariana Posada
      password: $2b$12$tvhrfpgpneEjautFmUsV.OMVR/AI9MCoequ8WTY/ZwYYB8Z7S28hy
    jsquirogac:
      email: jhosmarqc@gmail.com
      name: Shirley Quiroga
      password: $2b$12$vWBMf.OAttkuEr/6nQJU4OmXhoYnvvuvWXCBn8O15oieMoBHxaCja
    brangelc:
      email: joshbran02@hotmail.com
      name: Brenda Rangel
      password: $2b$12$h9qbyQLodJpaQH2OTlSZ.uhIdsZUgj30FQMguPBhj1jfANyPYSUWe
    dmejia:
      email: danielamejiaroncancio@gmail.com
      name: Daniela Mejia
      password: $2b$12$qanvi7DlDJg/EhfM3U9kP.vXRDrAHQsN/.nS/ErQeZcXf2XHHKaYW
    amlemusq:
      email: ana.maria.lemus@hotmail.com
      name: Ana Maria Lemus
      password: $2b$12$CRKWPqE97Sb.THSsc5Gx5e.TlmI/9BRq6h2F03b8Dnv7Ti2TBhU2u
    nrodasp:
      email: natalia.rodas93@gmail.com
      name: Natalia Rodas
      password: $2b$12$PaFTE1le8cz2Bc1MG7o10eAWWdmvN6SPpOdNYD5pphLthiv2J2usi
    oemoreirag:
      email: elizabeth.moreira38@gmail.com
      name: Elizabeth Moreira
      password: $2b$12$Su0Fj4whCjViDRi4AzHSae6XrH1qCKVkxXp/XoOTpCgg.rHltZG5C
    asariass:
      email: aarias.92@outlook.com
      name: Anny Arias
      password: $2b$12$5FRQZdiQwSORBFoY7Y79Hui3koX1Ec2KnB1TipZQ1FhhVGE.ZE.IG
    bjimenezd:
      email: damianjimenezbrenda55@gmail.com
      name: Brenda Jimenez
      password: $2b$12$tHVgpQRB3n6BHxsksWzXD.O.pInIADxmDMjb/DJvW340nefSOOPne
    nfernandez:
      email: nuria.fernandezga@udlap.mx
      name: Nuria Fernandez
      password: $2b$12$PsX3JJizFxpVDLigdSaNK.ZKPSNLgSyBYw5P533IO4mP555cJalTK
    imlopez:
      email: alisse.rl03@gmail.com
      name: Isabel Lopez
      password: $2b$12$SEZ3BFtft7WcA53k81dFxOo3hNIw41dNgmjf21cBNObSQuA4IK9Ru
    jlherrerab:
      email: jluixx@gmail.com
      name: Jose Luis Herrera
      password: $2b$12$/KqyNld/kk.vQUp8U/r5i.4BWqH7Em66/.WsQ2X7oAzqMW3k4PZ4q
    pltaform_dev_538:
      email: pltaform_dev_538@enfermeraenestadosunidos.com
      name: pltaform_dev_538
      password: $2b$12$WPnSVd/3BctWw4gsbK/Jq.4uIjciMmt6oER1O7TPfi3dtW/.KV8va
    mabolivare:
      email: alejandra77848@gmail.com
      name: Alejandra Bolivar
      password: $2b$12$8Kc.zdtBi39BJyOFgaUdnOvGERkE5mK8loCYfncvKa8psLhu0Bktm
    ldcarbajalo:
      email: lui.d.carorb1612@outlook.com
      name: Luis Carbajal
      password: $2b$12$7AginrpM7q6ZESxemhRBB.xbD303ECpZwbxadzbfNyvB.k9Bl6BkW
    lmoralesc:
      email: alizinha1@hotmail.com
      name: Luiza Morales
      password: $2b$12$Kpb.rZGKHGBRcue/wJ9atOJYyq.DM30kIOlJ1gVhJwlqkIzLBZoZW
    jfrodriguezm:
      email: yfrm240595@gmail.com
      name: Jessica Rodriguez
      password: $2b$12$5d2R95zZ0gNyzEjPCkE.YO.HWDBL8gGlWzvoxXJei4R6.ExWM4zrK
    smlunar:
      email: samuelxixx@gmail.com
      name: Samuel Luna
      password: $2b$12$CpOK7pXdnL.8pHbre98YsOplS2cYdeSzyw.qFzH/XFXTriUQqQeZ2
    arodriguezm:
      email: angie76roma@icloud.com
      name: Angelina Rodriguez
      password: $2b$12$Qdq6fvH9lxS/BE20smTbGOytCLMqG7HxQfaZTB6c.AW37il8wCDT.
    abahenac:
      email: acsa_dejcs@hotmail.com
      name: Acsa Bahena Carrera
      password: $2b$12$VQpya1sQG1x0TfoJKvAnJOjeS4yRE/4HNPbF/rdu4O6S70tGJzBam
    aacordobam:
      email: aacordobam@gmail.com
      name: Ana Maria Cordoba
      password: $2b$12$q8dkfNIbQLDWpv.aoHZ2tuCB73b80Ej6opHwS5yYQw9kSIvr2W012
    eyragan:
      email: enidyamile.ragan@gmail.com
      name: Enid Yamile Ragan
      password: $2b$12$TMV95.Jsby7BaUUDORnWoOdZwwvQbx5PVGfjKrM8WDbQnlJh/FWBa
    maruiz:
      email: maritzaadan122@gmail.com
      name: Maritza Ruiz
      password: $2b$12$e7TGRD4cmlWRLtK.KI7FAu65vlCKbN9.lVDtr7js6Q6/wmal/1LQG
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com
