credentials:
  usernames:
    cdgonzalezr_eeeu:
      email: elchristog@gmail.com
      name: Christian Gonzalez
      password: $2b$12$4AWFIxVL40AYHNdxrEbUQ.bvqTqbJV0tLLtY4myqWTklf4fhNKSZa
    jeamartinezcu:
      email: jeimy855@gmail.com
      name: Alejandra Martinez
      password: $2b$12$4AWFIxVL40AYHNdxrEbUQ.bvqTqbJV0tLLtY4myqWTklf4fhNKSZa
    lfmartinezs:
      email: lufermartinez1985@gmail.com
      name: Luisa Martinez
      password: $2b$12$4HfjCRGeboCMCvQyzD70.u3JMUvSV0mgDrDkMpwcZRXk4QprY9TSi
    testcustomer:
      email: elchristog@gmail.com
      name: Christian Gonzalez
      password: $2b$12$4AWFIxVL40AYHNdxrEbUQ.bvqTqbJV0tLLtY4myqWTklf4fhNKSZa
    yeseniaramirez:
      email: yeseniaramirez.ee@gmail.com
      name: Yesenia Ramirez
      password: $2b$12$PBbkQ3otfa.1DhdFVYH68OeoNXrCW7wkQGM7tVfZ7jwQbZvZ8ZKjq
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com
