credentials:
  usernames:
    cdgonzalezr_eeeu:
      email: elchristog@gmail.com
      name: Christian Gonzalez
      password: $2b$12$4AWFIxVL40AYHNdxrEbUQ.bvqTqbJV0tLLtY4myqWTklf4fhNKSZa
    jeamartinezcu:
      email: jeimy855@gmail.com
      name: Alejandra Martinez
      password: $2b$12$4AWFIxVL40AYHNdxrEbUQ.bvqTqbJV0tLLtY4myqWTklf4fhNKSZa
    lfmartinezs:
      email: lufermartinez1985@gmail.com
      name: Luisa Martinez
      password: $2b$12$4HfjCRGeboCMCvQyzD70.u3JMUvSV0mgDrDkMpwcZRXk4QprY9TSi
    testcustomer:
      email: elchristog@gmail.com
      name: Christian Gonzalez
      password: $2b$12$4AWFIxVL40AYHNdxrEbUQ.bvqTqbJV0tLLtY4myqWTklf4fhNKSZa
    jumaruizz:
      email: juliamariaruiz1@gmail.com
      name: Julia Ruiz
      password: $2b$12$Fmhn4ilWz2KfpUKz4NgzB.V7Uh0pICzsUu6RhdeNQH2RFbRAn6nC2
    yesntiranoes:
      email: escobar_9420@hotmail.com
      name: Yeisson Tirano
      password: $2b$12$qUVARWuLj0WBPzluAQG0M./r6rmI3G26ZxK4sk6u3KPNVehTXa6pC
    prmartince:
      email: marin.pris1983@gmail.comm
      name: Priscilla Cervantes
      password: $2b$12$SHze82ShGY/goUqugqqcL.lzaDHqC.lct9sGVK15YXjuZqyzf3jT2
    dslealc:
      email: didavidsantt@hotmail.es
      name: Santiago Leal
      password: $2b$12$mRSiosSXaSQchnkcUIsZ2OoHXCu0UJY46C4DkmXzyg.zDaB1dJr7S
    lgmatar:
      email: laumata21@gmail.com
      name: Laura Mata
      password: $2b$12$QocVs3Edg3XsBhq9wE.yHe1uoN0U6bOvZhhgoF1goLAFzofsFQuj2
    cgomezva:
      email: camila.gomezvasquez@gmail.com
      name: Camila Gomez
      password: $2b$12$9Mg5MHeENF4OfwUKHrcI0ujOnX7UAmsdxojE/FARHC9AYPeZWdI9S
    sdburitacam:
      email: saradanellyburitica@gmail.com
      name: Sara Buritica
      password: $2b$12$uk.FYLsUKHdrbroVfMsLj.CbM1bBeW8zwIC5hX3KbKkCd15VVcaq2
    lvrestrepom:
      email: vialaya@hotmail.com
      name: Luz Restrepo
      password: $2b$12$KVuBsj/PARlyKQX7JO1wg.H/0/gpjFgdmb8khQhnC.7TMPZn9OgQG
    marenas:
      email: ymarenascardenas@gmail.com
      name: Marcela Arenas
      password: $2b$12$Z4AijPo7xw2KIC1KMffgMediWjI67u0NSNBuQnRQveiwjJf2MYb.e
    alespitia:
      email: espitiaarizaangielorena@gmail.com
      name: Angie Espitia
      password: $2b$12$saspEq7hp2Xir3UFN9HOxOZf4Sw7ZNd4v4nJHYXZPXc5JS32x6zum
    mparboledap:
      email: Michellearboleda909@gmail.com 
      name: Paola Arboleda
      password: $2b$12$MePjMYL/3yDuiG68JrU07e.vzpQ6gbCeAOUpYZGJKDyS0MoA3RZgW
    iramirez:
      email: yeseniaramirez.ee@gmail.comm
      name: Ivette Ramirez
      password: $2b$12$cNpeIX8nZfsUa1viIl91SeHTUtQbts1VvhKwLExRyckCWKzWyxB4a
    tacalizarazo:
      email: taniakmila0810@hotmail.com
      name: Tatiana Lizaraso
      password: $2b$12$iJoa3kiqXyUZNJFh3JM7OOw.RNN2jkjYoRdHkHiS.ui.oMU2kvGPa
    bingleyodiaz:
      email: bingleyo.diaz@hotmail.com
      name: Bingley Ortiz
      password: $2b$12$gsJNdu16gcAYdeXqI5u6s.nfaQRNYFQI/Q1Re36Rh41VoSmjbpB9K
    ytmanrrique:
      email: yaneetyancemanrrique@gmail.com
      name: Yaneet Manrrique
      password: $2b$12$MxmAD1xgfdhxRCuq1u3Rt.73JjtLo9H5894D7L2cVwkryuJP54.OK
    ippadillac:
      email: paola6_17@hotmail.com
      name: Paola Padilla
      password: $2b$12$o7cYeNig1551ve0bBP8Jju9UtGiU0PmsMeTm0XNwjJukegeiyYvm6
    lvortizb:
      email: liseth1102@ocloud.com
      name: Liseth Ortiz
      password: $2b$12$bNhEKonEUVv4xf4H5eF34u9n6bWzDgMG72u7oIp3ZNHNXYPm.iXp6
    malejandraag:
      email: mayraariasga@gmail.com 
      name: Mayra Arias
      password: $2b$12$oEjiWzPuyLs8CrDXfH4mHOK6/vMDFAWszp191EuJhRmlP9/jIDXEu
    lgurbano:
      email: gelijulumar@gmail.com
      name: Lizagoretty Urbano
      password: $2b$12$PZTYN.aGa91jmkYCKYSoOugoMEt8EwhRkaJGV5/g3klU7lDvoD7ay
    jvduartea:
      email: vivi.duartea23@gmail.com
      name: Viviana Duarte
      password: $2b$12$4QNIVrpb9HPb2xVyNXnzQ.C51HK8apZASSB/WM8DirRnIm6QhkZTy
    dstephaniehr:
      email: dshernandezr23@gmail.com
      name: Dayanne Stephanie Hernandez Romero
      password: $2b$12$RX3rjHugTJ63YHDozVhGaOwXNc2w58Rr2.FjaZsqyS3sIfqDHKaO.
    erodriguezmr:
      email: eva66803@gmail.com
      name: Eva Rodriguez
      password: $2b$12$PIDhj9dsWv/Bj7LUnrU5yenyqShZ/XnDPzyn2FmxyJrxli9KvC.iO
    jacruzr:
      email: javierandrescruz01@gmail.com
      name: Andres Cruz
      password: $2b$12$o5ooT1q..xhismvyF1uk.enTuEqeRMRqkgzSrcfc8sw826aJxNETa
    tmosoresf:
      email: tatianaosoresfdez@gmail.com
      name: Tatiana Osores
      password: $2b$12$Ole9WkshxBxrxD3gCS2zaO/cx7Iw0/CJ1FpCpW3WQw0W7ZlYFJkn2
    lnoguera:
      email: lavaju1982@gmail.com
      name: Lady Noguera
      password: $2b$12$5vYxizZ/q6O8veH13cB48uf05kjoBi0zlJ2s.XMZHZAm3xyUKHfpK
    trafficker0231:
      email: trafficker0231@gmail.com
      name: trafficker0231
      password: $2b$12$lCiYym4L1bxOKXKxPOzLOOlnmTHaJC/Uq.TMzjfyUPj7w/RdpoDeK
    smperezg:
      email: marci.94@icloud.com
      name: Sleyter Perez
      password: $2b$12$6o4yu5IN7f7dGGVv0jpgPeEv1BJCuxqMiDT6so2u3nuGkDfTqqEju
    editor_0176:
      email: videoeditor@enfermeraenestadosunidos.com
      name: editor_0176
      password: $2b$12$.pxAEZaONqBvknuZf1lXn.Fd75vJmBvxMigA.GqjFl6mBQ21KUWmW
    amesquivelc:
      email: esquivelamanda22@gmail.com
      name: Amanda Esquivel
      password: $2b$12$Ln4VA9vNMRxvbaTaX2EyTuKeAfnIbRAwaKeiaEoMC6wjJDVOhlWhi
    lmvergaran:
      email: myriamverni@gmail.com
      name: Myriam Vergara
      password: $2b$12$Qg9ptxbIeSqhm/Ywo5BCSe5vjEw946ASfmsBg8m3eWdJy5bH9AvUO
    jacruzr_eeeu:
      email: javierandrescruz01@gmail.com
      name: Andres Cruz
      password: $2b$12$o5ooT1q..xhismvyF1uk.enTuEqeRMRqkgzSrcfc8sw826aJxNETa
    yabarreto:
      email: yumibase93@gmail.com
      name: Yumi Barreto
      password: $2b$12$H7JG6a1BCedpD1txFt3xD..pLi55UTMoYfkyC6s5h6.tIhr4AyhUq
    jasotog:
      email: julianitasogo@gmail.com
      name: Juliana Soto
      password: $2b$12$0eFGw.5AZ6r50PDVLdDni.mzRmVwpjLUuRXnpNvJRyxlcnHA2kmPK
    mmayangaf:
      email: meri.mf3092@gmail.com
      name: Merilin Mayanga
      password: $2b$12$1S3zbFUIJ7Jd34jUPOHsieT5Zuvxox9dSlyLIYG3YPmy528t3h1k2
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com
